### ISSUE TITLE
When crafting a post, "Help" link leads to lightbox which only contains another link which erases post content

### ISSUE THREAD

**Issue by blakeyrat-dailywtf** [apxltd/what-bugs#40]
Steps to reproduce:
1) Start composing a post (I'm using mobile mode for these steps; same bug exists in desktop mode)
2) Type some text
3) Click the tiny, virtually-invisible question mark icon next to the word "compose"
4) A lightbox opens with no actual help in it, but a link to another site
5) Clicking that link takes you to the CommonMark site without opening it in a new tab
6) Hit "Back" to return to your post

Expected results:

The text you typed is present; NodeBB is still in the state it was initially in before you clicked away to the other site

Actual results:

Your text is deleted; NodeBB is at the list of posts you were viewing before you started composing a new post

**Comment by Tsaukpaetra** [comment]
Noting that the microscopic ?-mark is very undiscoverable. It's also very difficult to hit on mobile, despite the browser's tendency to "fuzzy tap" links.
It seems that if you have "Open all external links in a new tab" enabled in User Settings, it does indeed open in a new tab (instead of current).

**Comment by BenLubar** [comment]
Moved to julianlam/nodebb-plugin-markdown#72
