### ISSUE TITLE
Post Edit Time Limit Too Short / Unfriendly Error Message

### ISSUE THREAD

**Issue by Choonster** [apxltd/what-bugs#71]
When trying to edit [this post](https://what.thedailywtf.com/topic/19207/can-we-have-an-official-nodebb-stylish-topic-now/54), I received this error:

![wtdwtf_editposterror_2016-03-31](https://cloud.githubusercontent.com/assets/878073/14154226/130c233c-f707-11e5-9b81-7b24b9e17534.png)
- This should display the time in a more sensible format, e.g. "7 days".
- The post edit time limit should be a lot longer, if not infinite. In a thread designed to act as a source of information rather than a regular discussion, a post may need to be updated with the latest information for quite some time after being posted.

**Comment by Tsaukpaetra** [comment]
Addendum: Option to "wikify" posts for non-mod editing or explicit-infinite-edit-time.

**Comment by BenLubar** [comment]
This also affects how old the posts fbmac can delete are.

**Comment by blakeyrat-dailywtf** [comment]
The error message is (mostly) irrelevant, as someone who's not eligible to edit the post should not be presented with the "edit post" button in the first place. (Unless it's a race condition and they happen to hit the edit button seconds before the timer expires; although in that case I'd argue the user "made it" and should be allowed to submit the edit anyway.)

The real problem here is not adopting that super-advanced sci-fi technology from 1984, where you grey-out or otherwise disable controls that aren't relevant to the current state of the application. This is not the only place NodeBB has that problem-- the "Thread Tools" menu contains it as well.

**Comment by BenLubar** [comment]
Moved to NodeBB/NodeBB#4668

**Comment by machado2** [comment]
The same could be said for post deletions

**Comment by Choonster** [comment]
Trying to edit the post after the time limit has expired has been fixed, but what about the time limit itself?

**Comment by BenLubar** [comment]
@Choonster what do you mean? The time limit is formatted properly now. Are you saying that a week isn't long enough to be able to edit a post?

**Comment by Choonster** [comment]
Yes, that was half of my original report. 1 week is definitely not long enough for informative threads.

**Comment by LB--** [comment]
Maybe there should be separate limits for original posts and subsequent posts.

**Comment by machado2** [comment]
why do we even have a time limit? if the post is mine I should be able to edit/delete it whenever I want

**Comment by Choonster** [comment]
I've just run into this limit again, is there any chance it could be increased or removed?

**Comment by Choonster** [comment]
@BenLubar Can we please increase the time limit? I just tried to update my post in the Game gifting area thread and realised that I can no longer edit it as it's been a week since I posted it.
