### ISSUE TITLE
Image links are overridden

### ISSUE THREAD

**Issue by LB--** [apxltd/what-bugs#84]
`[![](url-to-image)](url-to-page)` results in an image that when clicked actually leads to `url-to-image` instead of `url-to-page`

**Comment by BenLubar** [comment]
[Repro'd](https://community.nodebb.org/topic/8457/image-link)

**Comment by BenLubar** [comment]
@julianlam what is https://github.com/NodeBB/NodeBB/blob/e910d87e7c1c2475fd5450b9da5890b139a272e4/public/src/client/topic/posts.js#L307-L309 supposed to do?

**Comment by julianlam** [comment]
It prevents translation from failing by inserting a zero width space before the title if the title starts with `[`. 

Unfortunately this fix was needed because the translator is able to recursively translate keys. That is, you can use a translation key as a parameter. 

The way _that_ works is by not matching translation strings that begin with `[[`, and repeatedly translating the string until there are no more keys remaining. 

Easiest way to repo is to quote a post in a topic that begins with `[`.

**Comment by BenLubar** [comment]
@julianlam either you posted that on the wrong ticket or my link malfunctioned, because the code I meant to link doesn't touch brackets at all.

```
                if (image.parent().attr('href')) {
                    image.parent().attr('href', image.attr('data-src'));
                }
```

**Comment by julianlam** [comment]
Ah, my apologies. That fixes the link so it points to the image (there's a wrapImagesInLinks method somewhere). 

When the image is unloaded, the link ends up having its href set to the wrong location, so it is fixed once the image is loaded again.
